PSAppDeployToolkit/PSAppDeployToolkit

Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
There was on bracket too many.
=> deleted additional bracket from AppDeployToolkitMain.ps1

Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Fixed a TYPO in AppDeployToolkitMain.ps1, that caused the scheduled task on unblock application to fail
=> Fixed a TYPO in AppDeployToolkitMain.ps1, for unblock app

Examples/AdobeReader/Readme.txt, Examples/Office2013/Readme.txt
Great project guys!
I just did a clone and am looking at it, and noticed the Examples files referred to the documentation being in the wrong place, have updated.
=> Updated Example readme.txt's

Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Copy-File:
Flattens the source folder structure to the destination folder.
=> Added support for flattening folder structure within Copy-File

Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Fix issue PSAppDeployToolkit/PSAppDeployToolkit#364
=> Use universal date which is always locale independent

Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Apparently the last fix was needed in multiple places. This fixes them.
=> Added days-to-hours conversion for all functions

Toolkit/AppDeployToolkit/AppDeployToolkitConfig.xml
There is an issue with this file because you download everything here encoded as utf8 and this file specifies that its utf16. The encoding doesnt match and so the toolkit throws an error.
Issue #425
=> Change encoding to fix an issue

Toolkit/AppDeployToolkit/AppDeployToolkitConfig.xml, Toolkit/AppDeployToolkit/AppDeployToolkitExtensions.ps1, Toolkit/AppDeployToolkit/AppDeployToolkitHelp.ps1, Toolkit/AppDeployToolkit/AppDeployToolkitMain.cs, Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1, Toolkit/Deploy-Application.ps1
After over a year and a half of changes I believe it's time for a toolkit version bump.
=> Version bump to 3.8.0

Toolkit/AppDeployToolkit/AppDeployToolkitConfig.xml
In our corporation we use this language configuration for two years and works flawlessly, encountered zero confused users so far. 
With new version coming out I realized this could be easily added to project for everyone, as there are certainly many other happy czech administrators out there.
=> Add Czech UI language to XML

Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Adds powershell window renaming, in case it's visible to the user.
#454
=> Set Powershell window title

Toolkit/AppDeployToolkit/AppDeployToolkitHelp.ps1
Add Extensions.ps1 functions to the toolkit help window so functions from both files are listed.
Also changed .Add to .AddRange as that is supposed to be faster.
#459
=> Add Extensions.ps1 functions to the toolkit help window

Toolkit/AppDeployToolkit/AppDeployToolkitConfig.xml, Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1, Toolkit/Deploy-Application.ps1
Related to Issue #368 
Modified Deploy-Application.ps1 to add a repair deployment type
Modified config.xml to add the repair deployment type and all its translations (google translate helped with that...)
Modified the main.ps1 to handle the additional deployment type
=> Added repair functionality to the toolkit

Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Adds switch parameter -DisableRecursion for function Remove-Folder. Backwards compatible because the function works the same as previously without this switch.
Another way we could go about this is creating a boolean parameter with default - true.
#106
=> Add parameter -DisableRecursion for function Remove-Folder

Sources/Deploy-Application/Deploy-Application/Deploy-Application.csproj, Sources/Deploy-Application/Deploy-Application/Deploy-Application.exe.config, Sources/Deploy-Application/Deploy-Application/DeployApplication.cs, Sources/Deploy-Application/Deploy-Application/Properties/AssemblyInfo.cs, Sources/Deploy-Application/Deploy-Application/Properties/Settings.Designer.cs, Sources/Deploy-Application/Deploy-Application/app.config
Removed unneeded dependency System.Reflection and unused variable - we will use more reliable AppDomain.CurrentDomain.BaseDirectory. Recompiled for .Net Framework 3.5
=> Updated the project files

Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
This parameter allows us to change process priority right after the process starts.
Also removes unused variable $processStarted.
=> Add -PriorityClass for Execute-Process

Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
-ExitOnProcessFailure parameter allows us to stop Execute-Process from exiting the script so we can handle it in different way if needed.
It's a boolean by default set to true to retain current functionality.
Also adds missing parameter description for PriorityClass (got removed between last two PRs)
A good start for the following request:
#288
=> Add -ExitOnProcessFailure parameter for Execute-Process

Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Standard output is already handled this way so I added async reading also for the error stream.
WIP for #254 
PS: Changed Close() to Dispose() because Dispose calls Close() and also nulls variables so they can be garbage collected.
=> Add async reading of standard error stream to Execute-Process

Toolkit/AppDeployToolkit/AppDeployToolkitConfig.xml
These two languages needed a couple of fixes.
=> Fix Slovak and Czech translations

Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Regressing to the previous state of the part of the function that is causing slowdowns.
Also modifies Remove-InvalidFileNameChars so it doesn't always retrieve invalid filename characters on each function call but only once per script execution.
#495
=> Get-InstalledApplication regression

Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
WindowStyle Hidden doesnt usually work without this parameter on. CreateNoWindow will usually not work without this off.
This parameter changes the way the application is started. It is similar to entering a path into the Run dialog or into the Windows Explorer. If it is a file not an application, then the Shell will open it in a program assigned for this extension. The Shell doesnt stand for command shell but for operating system shell. It also changes how Working Directory is used.
**If this parameter is set to $true there is no output/error stream. Only an exit code. Default value is $false which was also the case before this PR, however you couldnt change it through parameters previously.**
Expanded description for WindowStyle, CreateNoWindow and WorkingDirectory
=> Add -UseShellExecute for Execute-Process

Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Allows Execute-Process to return an object if **PassThru and NoWait are both specified**. Normally we don't have an output since the process hasn't stopped yet but instead of returning nothing we can return process id, process name and process handle if a user wants to check something through them.
#513
=> Add a return value if NoWait and PassThru are specified

Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Change the function so it allows restarts of the computer even in silent and very silent deploy mode.
Adds NoSilentRestart parameter for the function. Default is True to retain previous behavior of the function.
#359
=> Show-InstallationRestartPrompt restart in silent deploy mode

Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Decreases number of loops in the function so it takes less time to enumerate all processes. 
Removed -Unique parameter for Sort-Object so the output includes processes with the same name but different id.
=> Get-RunningProcesses improvements

Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
=> Fix missing assignment for $envOSVersion

Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
If the PATH variable is modified and no longer contains path to System32, the toolkit doesnt work correctly. This fix changes those paths so they dont rely on PATH.
=> Do not depend on PATH for system .exe paths

.github/ISSUE_TEMPLATE/bug_report.md
Expanded Toolkit version description and added Powershell version
=> Issue Template update

Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1, Toolkit/Deploy-Application.ps1
Reworked the function, added new parameters.
Also added a couple of missing -Source parameters on some Write-Log uses
=> Set-Itempermission fixes and improvements

Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Renames Get-ScheduledTask to Get-SchedulerTask and adds an alias Get-ScheduledTask if no such function exists.
Fixes #373 
Fixes #558
=> Change Get-ScheduledTask and add an alias

CHANGELOG.txt, Toolkit/AppDeployToolkit/AppDeployToolkitConfig.xml, Toolkit/AppDeployToolkit/AppDeployToolkitExtensions.ps1, Toolkit/AppDeployToolkit/AppDeployToolkitHelp.ps1, Toolkit/AppDeployToolkit/AppDeployToolkitMain.cs, Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1, Toolkit/Deploy-Application.ps1
Version bump. 
Updates changelog with missing entries.
=> Version bump to 3.8.3

Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Also adds logging for Enabling inheritance
=> Set-ItemPermission Synopsis fixes

Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Added a couple of function help entries.
Also adds variables LocalUsersGroup, LocalPowerUsersGroup, LocalAdministratorsGroup that you can use to get translated group names.
Fixes #416
Fixes #150 
=> Function help expansion

wiki/Building-an-Adobe-Reader-installation-with-the-PowerShell-App Deployment-Toolkit.md, wiki/Convert-RegistryPath.md, wiki/Invoke-HKCURegistrySettingsForAllUsers.md
Just changed documentation block in wiki file. 
For examples it's better to use MD code block 
=> Patch example docu

CHANGELOG.txt, Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
- Added function Set-Shortcut that allows you to change existing shortcuts
- Changed New-Shortcut:
- BREAKING CHANGE: IconIndex parameter is now an Integer. It was previously incorrectly specified as a String.
- Reworked the way this functions sets shortcut to run as admin
- Added additional checks for the input Path in order to provide better log messages and better handling of relative paths
- Improved function help text
Fixes #273
=> Add function Set-Shortcut

CHANGELOG.txt, Toolkit/AppDeployToolkit/AppDeployToolkitConfig.xml, Toolkit/AppDeployToolkit/AppDeployToolkitExtensions.ps1, Toolkit/AppDeployToolkit/AppDeployToolkitHelp.ps1, Toolkit/AppDeployToolkit/AppDeployToolkitMain.cs, Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1, Toolkit/Deploy-Application.exe.config, Toolkit/Deploy-Application.ps1
=> Version bump and encoding change

CHANGELOG.txt, Toolkit/AppDeployToolkit/AppDeployToolkitMain.cs, Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Check the changelog for the list of all changes
**Includes changes from this PR - #621**
Fixes #455 
Also gives timers unique names and centralizes parameter resolving.
=> Multiple bugfixes

Sources/BetaToolkit/Deploy-Application.ps1, Testing/Deploy-Application.ps1, Toolkit/AppDeployToolkit/AppDeployToolkitConfig.xml, Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1, Toolkit/Deploy-Application.ps1
I only changed Comments so no Harm can be done
Only changed Code Comments
=> Minor spelling fixes

Toolkit/AppDeployToolkit/AppDeployToolkitConfig.xml
=> Finnish translation for message UI.

Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1, wiki/Get-InstalledApplication.md
No Code was changed
Basicly all I did
yes
=> Get-InstalledApplication Doku update

Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
=> Fixes the error returned by the scheduled task created by Block-AppExecution

Toolkit/AppDeployToolkit/AppDeployToolkitConfig.xml
=> Fixed typo

Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
=> Fix app deploy toolkit main failed to load

Toolkit/AppDeployToolkit/AppDeployToolkitConfig.xml
=> Fix Russian UI messages

Toolkit/AppDeployToolkit/AppDeployToolkitConfig.xml
=> Improvements for Russian UI

Sources/Template_New-Function.ps1
I changed the old Link to a new functioning one and added another helpfull one.
=> Renewed and added Source

Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
I'm frustrated when I try to change the window location and PSATK doesn't have options such as "BottomLeft" but it has "BottomRight" so I added the functionality.
=> Add new WindowLocations (Top, TopRight, TopLeft, Bottom, BottomRight)

Toolkit/AppDeployToolkit/AppDeployToolkitConfig.xml
1.
Programme Schließen --> Programme schließen
2.
ALT+W = Button Continue
ALT+S = Button Close
ALT+A = Button Defer
=> de translation

CHANGELOG.txt
=> Bump version in changelog

Toolkit/AppDeployToolkit/AppDeployToolkitConfig.xml
Fixes #872
Added Turkish language from https://gist.github.com/ll4mat/883eb0fd1f3a19b89de039068f66cda5, as referenced in https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/issues/872.
Note that the gist also recommends some further language tweaks for uninstall, but we have that problem across the board for all languages (dialogs on uninstall mentioning Install).
=> Add Turkish language support

Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
It seems more likely that the source of this message should be $appDeployToolkitName and not $appDeployToolkitExtName.
=> Fix incorrect source variable

Testing/Execute-ProcessAsUser.Tests.ps1, Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Fixes: #1026
First reported here:https://discourse.psappdeploytoolkit.com/t/execute-processasuser-fail-in-psadt-3-10-1/5645/4
- 3.10.0 introduce a Try/Finally block around most of the code in the Process block of Execute-ProcessAsUser.
- This meant that nested Try/Catch/Throw statements within here were not getting thrown out of the function. The test to exit the function when no users were logged on was getting snagged in this Try block, causing the Finally block to try and clean up a scheduled task that has not been created.
- The outer Try block was moved to just before the creation of the scheduled task, since its Finally block was just there to mop up the scheduled task.
- A catch block was added to this to rethrow any exceptions triggered within.
- Pester test extended to confirm …
=> Prevent Execute-ProcessAsUser throwing terminating error when no user logged on

Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
- Install name no longer goes through a list of illegal characters - only double quotes need to be substituted as they trip up the calling of VBScript. Since they are just in names/titles, they are replaced with two single quotes.
- $SchInstallName was a sanitized version of $InstallName, now there is $SchInstallTitle as a sanitized version of $InstallTitle.
- [System.Security.SecurityElement]::Escape used to escape entire command before insertion into the XML. This properly esacapes characters like & and ".
Fixes: #1034
Running a series of tests with Block-AppExecution with $InstallName and $InstallTitle set to contain all the characters that were previously being replaced - e.g:
```powershell
[String]$installTitle = @'
Hi "there" $!'`();\*?{}[]<>|&%#~@'
'@
```
=> Fix escaping of invalid characters in Block-AppExecution

actions_bootstrap.ps1, docs/Invoke-ADTAllUsersRegistryAction.md, docs/Invoke-ADTObjectMethod.md, docs/Mount-ADTWimFile.md, docs/New-ADTErrorRecord.md, docs/New-ADTValidateScriptErrorRecord.md, docs/PSAppDeployToolkit.md, docs/Remove-ADTFile.md, docs/Resolve-ADTErrorRecord.md, docs/Start-ADTProcess.md, src/PSAppDeployToolkit.build.ps1, src/PSAppDeployToolkit/Public/Invoke-ADTAllUsersRegistryAction.ps1, src/PSAppDeployToolkit/Public/Resolve-ADTErrorRecord.ps1, src/PSAppDeployToolkit/Public/Start-ADTProcess.ps1
This PR incorporates Docusaurus into our module's build system, using our custom fork of the module to parse our markdown exports, generate the necessary mdx files, then compressing them as an artifact for downloading at the end of a successful action.
This has been tested locally and confirmed to build on my system.
=> Incorporate Alt3.Docusaurus.Powershell into our module build system

.github/workflows/wf_Windows.yml, docs/New-ADTTemplate.md, src/PSAppDeployToolkit.build.ps1, src/PSAppDeployToolkit/Public/Show-ADTBalloonTip.ps1
The build system has been uploading a zip file of zip files, which is awkward and means everyone has to download the entire zip file when they may only want an aspect of it. This PR addresses that.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
=> Rework module build system to upload individual zip files

src/PSAppDeployToolkit/Public/Show-ADTInstallationWelcome.ps1
Fix incorrect parameter name in help text
it wasn't
=> Fix incorrect parameter name in help text

src/PSAppDeployToolkit/Strings/nb/strings.psd1
Updated some of the Norwegian wording.
=> Updated wording of Norwegian.

src/PSAppDeployToolkit/Strings/nl/strings.psd1
Improved overal text and consistancy of word use.
=> Update strings.psd1 (NL)

src/PSAppDeployToolkit/Public/Write-ADTLogEntry.ps1
Map Severity.Warning to $WarningPreference to allow muting warnings
=> [feat] Respect WarningPreference in Write-ADTLogEntry

src/PSAppDeployToolkit/Strings/de/strings.psd1
As discussed, here are a few small updates to the german translation for the newly merged dialog rework
=> German translation for dialog rework

.github/CONTRIBUTING.md
label was wrong in URL for "help wanted" hyperlink. license file was dead link. Updated to COPYING.Lesser
=> Hyperlink updates to CONTRIBUTING.md

src/PSAppDeployToolkit/Strings/fi/strings.psd1
DialogMessageNoProcesses, the text has Install and Repair in English instead of Finnish. Changed "Install" to "Asenna" and "Repair" to "Korjaa" (Since the buttons say this anyway).
=> Update strings.psd1 (for Finnish language)

src/PSAppDeployToolkit/Public/Start-ADTMsiProcess.ps1
Wasn't factoring in whether the user who'd be running the MSI could write to the log location or not.
=> Fix the logging setup for `Start-ADTMsiProcessAsUser`.

src/PSAppDeployToolkit/Public/New-ADTZipFile.ps1
=> Make `New-ADTZipFile` work properly.
