PSAppDeployToolkit/PSAppDeployToolkit

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
The Hashtable is storing $LogfilePath instead of $LogFileName for
LogfileName. This would result in the log being written to "Path\to\log"
+ "Path\to\Log\File" instead of "Path\To\Log" + "File". The log would error when trying to write log
Messages to "Path\To\Log\Path\To\Log\File"
> Logpath referenced instead of logname in Hastable  when archiving logs

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Due to differences in CWD between .NET and PoSH the Install-MSUpdates
procedure fails.
Changing $file to $file.FullName resolves the issue.
Fully tested in OTA envorinment on 12 different windows 7 devices.
> .NET vs PoSH CWD differences

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Added escape characters to $LogTime, for example Finnish culture info changes ":" to "." and cmtrace will parse it wrong. 
Bad formatting (seen in cmtrace):
[Initialization] :: Installation is running in [Interactive] mode.		1.1.1601 0.00.00	0 (0x0000)
->
Log file:
<![LOG[[Initialization] :: Installation is running in [Interactive] mode.]LOG]!><time="13.02.20.943120" date="03-06-2019" component="PSAppDeployToolkit" context="Computer\User" type="1" thread="1172" file="AppDeployToolkitMain.ps1">
Working (seen in cmtrace):
[Initialization] :: Installation is running in [Interactive] mode.	PSAppDeployToolkit	13.3.2019 13.41.13	7356 (0x1CBC)
->
Log file:
<![LOG[[Initialization] :: Installation is running in [Interactive] mode.]LOG]!><time="13:34:13.930+120" date="03-13-2019" …
> Write-Log function escape character fix

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
The parameter -MsiExecWaitTime is creating a timespan variable through New-TimeSpan when its not specified but when it is, its created through the variable which creates a timespan variable with incorrect value set, because it assumes you want to use that value for Ticks not seconds. This change fixes it by changing it to an integer and then creating a new timespan variable where this integer is used for seconds.
> Execute-Process -MsiExecWaitTime parameter fix

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Allows putting different MSI Installers for x86 and x64 by naming them .x86.msi and .x64.msi instead of .msi.
For example a folder containing "7z1900.x86.msi" and "7z1900.x64.msi" will install the proper MSI depending on the OS Architecture
> Added Support for Zero Touch MSI Deployment with different System Architecture Dependency

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Only replace invalid characters, not an entire segment since that would have removed localized app display names.
Removing the replacement entirely is not a good idea since we may have control characters.
> Get-InstalledApplication should only replace invalid characters

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
The dynamic banner size broke this function, making it not display anything and just post a long message into the log. This is a fix for it.
> Show-InstallationProgress fix

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Fixes the issue where the time remaining doesn't show more than 24 hours.
Credit to adipiciu for the fix.
> Show-InstallationRestartPrompt timer fix

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Replaces function aliases with their full names and fixes the description of the PersistPrompt parameter.
> Replace function aliases with their full names and fix conflicting documentation

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
The function goes through all active-setup entries in the HKCU for the specified name and removes them however not every user might have logged in to have it written via Active Setup so this would lead to a lot of error messages where the function would not find the registry key in the user's hive.
This change adds a check to test whether the key exists before removing it.
> Fix Set-ActiveSetup purging error

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Powershell 2.0 doesn't support the **-in** parameter(at least not with the build that gets released with win 7).
> Removed the -in operator

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Due to how Invoke-HKCURegistrySettingsForAllUsers loads user registry hives, Active setup purging did not test the registry key correctly. This fixes it, 
#439
> Fix Set-ActiveSetup purging incorrectly testing registry values

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.cs
- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Disable/grey out the X(close) button on the Installation Progress window so the user knows the window can't be closed this way. Also disables it in the context menu.
> Grey out the X(close) button

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Removed UninstallString check, as ProductCode is always retrieved from PSChildName in Get-InstalledApplication
> Remove-MSIApplications function failed for MSI's with ARPNOREMOVE #449

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
This patch adds the function Remove-InvalidFileNameChars to the toolkit and is used in places where filename was being validated before. I also added removal of invalid chars to the New-Zipfile command since it doesn't have one, causing it to fail while creating zip files when an invalid character is specified.
#452 
possibly #397
> Add function Remove-InvalidFileNameChars

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
When this function looks for the specified application, it will skip entries that look similar to updates. However, the user doesn't get any information about this happening. This pull request fixes it by writing the number of such entries to the log. #438 
We could also list all the entries that are skipped however such list could be very long.
This pull request also adds a log entry when no result is found as that is currently missing too.
> Get-InstalledApplication - add more log messages

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Adds a switch to the function that gets file version info, in case they want to use Product Version instead. Also removes version modification, that returns parts of the version when theres a space.
#409
> Add -ProductVersion to Get-FileVersion

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Execute-MSI uses Remove-InvalidFileNameChars to remove invalid chars from the name, however it then uses -replace operator to remove spaces and Powershell considers it a parameter so this PR adds brackets around the function to fix this issue.
Also fixes the comment above the Remove-InvalidFileNameChars function that specifies incorrect function.
> Fix Execute-MSI issue related to Remove-InvalidFileNameChars

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
CMTrace requires all parameters to be filled in, otherwise the highlighting doesn't work.
This PR sets the -Source to Unknown unless it is defined in the parameter.
> Change default value for -Source parameter for Write-Log

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Currently Execute-Process is one of the functions that fails on error even if ContinueOnError is specified because this parameter is used for ignoring exit codes and not handling errors. This PR fixes it by adding the ability to ignore all exit codes through -IgnoreExitCodes "*" while -ContinueOnError will be used for ignoring errors that occurred inside the function as expected.
Also fixes a couple of typos and fixes -PassThru because currently, it makes the function ignore exit codes. 
Rewords log entry for when this function is used for an MSI installation but another installation is already running.
#125
> BREAKING CHANGE: Modify Execute-Process -ContinueOnError behavior

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Adds parameters -NoWait -IgnoreExitCodes -PriorityClass and -ExitOnProcessFailure for the function Execute-MSI
By adding parameter -ExitOnProcessFailure we are able to stop the function from exiting the script on an error code so we can handle it differently. #288 
Also fixes a typo.
> Add more parameters for Execute-MSI

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Adds -RepairFromSource for Execute-MSI to support msiexec /fv
Currently only /f is supported which doesnt rewrite cached msi on repair.
If a user supplies a product code, the source location is taken from registry, which may or may not exist at that point. The source msi may not even exist. This is being handled by msiexec and not our toolkit. So the msiexec will return an error through Execute-Process. Won't be a customized log entry.
#266
> Add -RepairFromSource for Execute-MSI

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Execute-Process was changed and Remove-MSIApplications uses it through Execute-MSI. -ContinueOnError needs a new description.
> Fix parameter description for Remove-MSIApplications

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Adds -WorkingDirectory for function Execute-ProcessAsUser so the task may execute with a specified working directory. There is a check for whether the directory exists however not a terminating one, because some paths are recognized by task scheduler but not by powershell without expansion (example %windir%)
#210
> Add -WorkingDirectory for Execute-ProcessAsUser

- Toolkit/AppDeployToolkit/AppDeployToolkitConfig.xml
- Toolkit/AppDeployToolkit/AppDeployToolkitExtensions.ps1
- Toolkit/AppDeployToolkit/AppDeployToolkitHelp.ps1
- Toolkit/AppDeployToolkit/AppDeployToolkitMain.cs
- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
- Toolkit/Deploy-Application.ps1
Adds sanitization for $installTitle, $ReferredInstallTitle and $ReferredInstallName
Restores the previous powershell window title in Exit-Script
$app* variables no longer have all space characters removed, only the beginning and the ending ones. $installName still removes spaces from these variables, like before, because it is used for file names.
$installName changes are collapsed to one line and also removed the Remove-InvalidFileNameChars function from it, since we already use it on all variables that this variable can contain.
#491 
#264 
Includes version bump
> Improved handling of title variables

- Toolkit/AppDeployToolkit/AppDeployToolkitExtensions.ps1
- Toolkit/AppDeployToolkit/AppDeployToolkitMain.cs
- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
- Toolkit/Deploy-Application.ps1
Removes BOM from Toolkit files that were encoded with UTF8 with BOM.
Make sure we are reading the xml file as UTF8.
> Remove BOM from toolkit files

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Removes huge empty gap on some variations of the window.
Fixes some text entries not being centered.
Removes unused variables.
Fixes missing install title  if -CloseApps is present.
Makes CloseApps ListBox a little bit wider.
#470 
#2
> Fix visual bugs in Show-InstallationWelcome

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
- Fix issue with $envOSVersionRevision not being populated on Windows 8 because the "UBR" registry value is only being checked if "$envOSVersionMajor = 10"
- Fixed an issue where the correct ProgramFiles and CommonProgramFiles paths were not populated if the Toolkit was launched from a 32-bit process on a 64-bit OS.
> Fix bug with $envOSVersionRevison and Normalized ProgramFiles and CommonProgramFiles Path Variables

- Toolkit/AppDeployToolkit/AppDeployToolkitConfig.xml
- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Adds config paths for installations where RequireAdmin is False.
Also changes default -Source value for Write-Log to a more useful value: it will be set to Parent's function name and if not inside a function then the name of the script. If not inside a function or a script, then the value will be set to 'Unknown'
#482 
#503
> Add config paths without admin rights

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
The window wasn't scaling with bigger text previously and didn't start in the correct location on the screen on different windows Scaling.
This PR fixes starting location of the window, changes it to center of the screen as default but also adds TopCenter as an option for this function. #171 
Location is now correctly set even when Windows Scaling is different.
Height of the window is now not limited and therefore no text will get cut off. #205 
Removed unused variables and improved performance due to no need to go through a huge xml string to replace pseudo-variables.
The status message is now centered correctly.
New window:
New window with huge custom text:
> Improvements for Show-InstallationProgress

- Toolkit/AppDeployToolkit/AppDeployToolkitConfig.xml
- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Show-InstallationWelcome was slightly modified:
- separated the Installation Title in the form so its more clear for the user
- modified buttons top and bottom spacing so its consistent with and without countdown
- fixed padding around CloseApps list caused by whitespace inside the xml config
Show-InstallationPrompt was reworked so the window scales with the amount of text entered and removed unused space. If there is no icon specified, the text will scale the entire width too. Buttons now look the same like in Show-InstallationWelcome
> Show-InstallationPrompt and Show-InstallationWelcome visual improvements

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Previous PR added NoSilentRestart however there is a problem with Start-Process which needs to load to main script for asynchronous UI load and forwards this function's parameters to it. NoSilentRestart doesn't exist there so it fails to load. This PR fixes that issue.
Additional improvements:
-trigger timeout and reboot in another instance of powershell so the main toolkit process can continue with logging
-added SilentCountdownSeconds parameter because users might want to specify a separate timer for silent mode reboot. For example if a user is logged in, you give them 5min to save their work and reboot, but when no one is logged in, you can trigger reboot right away since no one needs to save their work.
-expanded parameter descriptions to include default values
-added an example and a …
> Show-InstallationRestartPrompt fixes for silent mode

- Toolkit/AppDeployToolkit/AppDeployToolkitConfig.xml
This button is misleading for the user. Microsoft uses Restart Later buttons to extend the duration of time left before a reboot is triggered. The function Show-InstallationRestartPrompt however does not extend the duration even though the button is called Restart Later. It only minimizes the window. So this PR renames the button to Minimize. Fixes #276
> Rename Restart Later to Minimize

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Execute-Process -PassThru no longer ignores exit codes so the places where Execute-Process is called with -PassThru now need to not exit the script on process failure.
Fixes #512
> Execute-Process -passthru use throughout the toolkit fix

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Some of the registry paths used by the toolkit are still using powershell drives that are akin to command aliases and can be changed. This PR changes them to full paths.
> Use full registry paths instead of PSdrives

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
The function is now faster due to restructuring of the code.
The function will now warn about use of -SID parameter for hives that aren't HKCU.
Fixed a bug where the function would not convert the keys from HKCU to HKU\$SID if the key started with Registry:: already.
> Convert-RegistryPath improvements

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
- I tested the toolkit with my changes. Made sure it doesn't break other code.
- I updated the documentation with the changes I made.
- The code I changed has comments with explanation.
- The enconding of the file wasn't changed. It is still UTF8 without BOM.
Some of our customers had problems with this function because of following bug:
https://www.kapilarya.com/what-is-defaultuser0-account-in-windows-10-and-how-to-remove-it
So we use `Get-UserProfiles | Where-Object { $_.NTAccount }` every time
> improved Get-UserProfiles function

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
This PR:
- fixes a bug where a negative index could be sent to SubString causing a crash
- when cmd is used as path, just like powershell, it has to be started silently otherwise a window pops up so this PR fixes that
- adds more logging so its more clear when this function is used to start powershell or cmd
> Execute-processasuser - Fix possible negative index for SubString

- Toolkit/AppDeployToolkit/AppDeployToolkitConfig.xml
- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Since $envTemp points to c:\windows\temp and the folder has limited permissions for Administrators by default, it has to be changed again. ProgramData seems like the best option other than ProgramFiles which is used for programs themselves. ProgramData is also hidden by default.
ProgramData is read only to users by default so we need to change the no admin rights log dir to a user writable location for when the toolkit runs without admin rights. Not many such folders exist. One of the best locations is LocalAppData since those folders dont get erased without reason and are user writable.
Also modifies Block and Unblock AppExecution functions so they get bypassed if admin rights are not requested because the functions require elevated permissions to function.
Fixes #526
> Change Un/Block-AppExecution so it doesn't run without admin rights

- .github/PULL_REQUEST_TEMPLATE.md
- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Set READ permissions to BUITLTIN\Users so they can get the popup message
Added Set-Permission function to make it easier to set permissions
- [TODO] I updated the documentation with the changes I made.
> Fix for tempory folder issue for blocked execution

- CHANGELOG.txt
- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
This function is used in multiple registry functions that log their actions by themselves and this function adds unnecessary clutter to logs. This patch disables logging in this function by default but allows it to be enabled if needed.
Example:
> Disables Convert-RegistryPath logging by default

- CHANGELOG.txt
- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Also expands logging.
-ExecuteForCurrentUser is enabled by default to retain previous functionality
> Add -ExecuteForCurrentUser for Set-ActiveSetup

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
On win7 Show-InstallationProgress is not centered. This fixes it.
> Fix Show-InstallationProgress window not being centered

- CHANGELOG.txt
- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
- Changed Show-InstallationWelcome:
- The buttons are now wider
- The listbox is also wider so it is aligned with buttons
- The countdown is now bigger and in bold
- The appname is now in bold to be more visible
- The function now closes processes by name not by ID
- Fixed the hidden abort button not working on toolkit timeout
- Performance improvements
- Changed Show-InstallationPrompt:
- Fixed the hidden abort button not working on toolkit timeout
- The buttons are now identical in size and position to the ones in Show-InstallationWelcome
- Increased the gap between the banner and the text when the message is too short
- Changed Show-InstallationRestartPrompt:
- Reworked the window to look consistent with Show-InstallationWelcome
- Changed Show-InstallationProgress:
- Reworked the …
> Multiple fixes for UI and -CloseApps

- CHANGELOG.txt
- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Change the behavior of the function Execute-Process and Execute-Msi to check boolean and switch parameters with $PSBoundParameters.ContainsKey()
Fix for #580
> Fix Boolean parameters not being passed to Execute-Process

- CHANGELOG.txt
- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
- Fixed the toolkit checking task scheduler services twice
- Fixed the toolkit not creating $app variables if they are not created in Deploy-Application.ps1
- Reworked Close-InstallationProgress so it waits a couple of seconds in case the window is not opened yet
- This fixes an issue where the Show-InstallationProgress dialog would not get closed on slower machines where Close-InstallationProgress was called right after Show-InstallationProgress
This patch also gets rid of sub functions inside Show-WelcomePrompt. Also fixes a couple of minor issues.
#532 #448
> Close-InstallationProgress fix

- CHANGELOG.txt
- Toolkit/AppDeployToolkit/AppDeployToolkitMain.cs
- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
A lot of performance improvements in this one.
Changed some function signatures to the ones specified in the official documentation.
Removed some redundant code.
Only loading assemblies once.
Execute-ProcessAsUser now escapes XML characters prior to creating an xml file.
Added log messages to some Show- functions when the function is being bypassed due to deploy mode.
Set-ActiveSetup now doesn't execute the StubPath if the registry key for it exists in the CU hive with IsInstalled set to 1.
Show-InstallationWelcome now closes processes correctly if the user has reopened them while the window was running.
Fixes a couple of typos.
Fixes an issue with Set-ItemPermission where SID translation did not work correctly #598
> Multiple fixes

- CHANGELOG.txt
- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Removes backslashes at the start of $envLogonServer 
Fixes #155
> Remove backslashes at the start of $envLogonServer

- CHANGELOG.txt
- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
If you run multiple toolkits in the same powershell session, these variable do not get reinitialized because they are not empty. This causes bugs, for example the log file is the same even though the toolkit is not. This PR resolves it but not if the script is exited without Exit-Script.
Fixes #567
> Clear a couple of global variables on exit

- CHANGELOG.txt
- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Adds function Get-Shortcut
Removes undocumented ability for parameter -IconLocation to accept <icon path>,<icon index> since we have -IconIndex
Fixed IconIndex 0 not being passed correctly
> Added function Get-shortcut

- CHANGELOG.txt
- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
- Changed Show-InstallationPrompt:
- The function now doesn't call Close-InstallationProgress when running in async mode
- Changed the way Execute-MSI handles paths for Transforms and Patches:
- The only accepted separator is now a semi-colon. Commas can be a part of the paths now.
- Double quotes are removed from the paths before the entire string is wrapped in double quotes. 
Fixes #604 
> Execute msi transform separator

- Toolkit/Deploy-Application.ps1
Making the "Perform X Tasks Here" comments consistently use two number signs.
-- N/A
-- N/A
> Consistent use of two number signs for comments

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Since `/f` implies `/fomus`, `/fv` effectively strips away _omus_, so nothing is actually repaired.
`$RepairFromSource = $true` now uses `/fvomus`.
(I have been using this change in production already)
(no changes required, docs do not go into detail about implementation)
(comments added to commits but not code)
> Add 'vomus' instead of 'v' when $RepairFromSource = $true

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
- wiki/Toolkit-Variables.md
Add $IsMultiSessionOS Toolkit Variable. This allows users to easily check if the current operating system is Windows Multi-Session or not. Keying off of $envOSName at guidance from a coworker and Microsoft.
PS Sorry for PR #695.
> Add $IsMultiSessionOS Toolkit Variable

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Be sure to also set EscapedPath and EscapedParameters in the code branch that creates a .vbs in the event you are trying to run PowerShell as $RunAsActiveUser - as these newer variables are referenced further down during scheduled task creatiion
> Execute-ProcessAsUser VBScript that will start PowerShell fix

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Escaped path to work with spaces like "C:\Program Files\PSAppDeployToolKit"
> Escaped path to work with spaces like "C:\Program Files\PSAppDeployToolKit"

- Toolkit/AppDeployToolkit/AppDeployToolkitConfig.xml
Sets `Toolkit_LogDoNotAppend` to `False` as per its commit message (1d116e219bd20df3f4905248f35054d69bd1bcbf).
> - Set `Toolkit_LogDoNotAppend` to `False`.

- Examples/AdobeReader/Readme.txt
- Examples/Office2013/Readme.txt
Follow-up to de7fa6394aa6d4b69cb65874b2c1865e88488b3b that renamed the former `PSAppDeployToolkitAdminGuide.docx` document to `PSAppDeployToolkit.pdf`.
> Change PSAppDeployToolkitAdminGuide.docx reference to PSAppDeployToolkit.pdf

- Sources/BetaToolkit/AppDeployToolkitMain.ps1
- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Invoke-HKCURegistrySettingsForAllUsers called Get-UserProfiles and it returned defaultuser0. It 'interacted' with the defaultuser0 profile during a SCCM OSD task sequence in Post-Installation steps. It unloaded the defaultuser0 profile which caused CloudExperienceHostBroker.exe to reset OOBE and reboot.
[Post-Installation] :: Load the User [COMPUTERNAME\defaultuser0] registry hive in path [HKEY_USERS\S-1-5-21...
[Post-Installation] :: Unload the User [COMPUTERNAME\defaultuser0] registry hive in path [HKEY_USERS\S-1-5-21...
> Exclude defaultuser0 from Get-UserProfiles

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Issues with previous code:
- /IM only copied files with different timestamps, switched to /IS to copy everything, to match native PowerShell behaviour
- /NJH /NJS /NS /NC /NP /NDL /FP switches added to minimise Robocopy verbosity (NJH = No Job Header; NJS = No Job Summary; NS = No Size; NC = No Class; NP = No Progress; NDL = No Directory List; FP = Full Path)
- Robocopy now launched with -CreateNoWindow rather than -WindowStyle Hidden. A recent 3.9.4 commit enables -UseShellExecute when supplying -WindowStyle Hidden, which makes StdOut inaccessible.
- Previous Robocopy log was unnecessary and was overwritten on each command execution. Now StdOut is captured and sent to Write-Log.
- Robocopy disabled if -Path contains *, as Robocopy only …
> Robocopy-changes

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
I kept getting property errors while running in strict mode and found the setup in `Get-RunningProcesses` could probably stand to do with a re-write.
Its probably not important enough for 3.9.4, but it does go to show again what `Set-StrictMode` finds that previously would go unnoticed. https://learn.microsoft.com/en-us/powershell/module/microsoft.powershell.core/set-strictmode?view=powershell-7.4
* Significantly reduce code depth by adopting a "never-nesting" approach. This makes the code more readable by not having to keep track of how many branches down the chain you are.
* Remove almost all else branches by performing early returns where smart to do so. This goes hand in hand as part of never-nesting and keeps the code more readable.
* Speed up code by not looping through …
> - Re-write `Get-RunningProcesses`.

- Toolkit/AppDeployToolkit/AppDeployToolkitConfig.xml
- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
- Order of a few params in Write-Log / config.xml have changed (just for aesthetics to group the related params). This might technically be a breaking change, although very unlikely people would be using 10+ positional parameters.
- Default is <Toolkit_LogAppend>True</Toolkit_LogAppend> (which behaves the same as 3.9.3). Turn that to false and you have managed log rotation.
- Handling is combined with the max log size routine, which has now moved from the End to the Begin block of Write-Log.
- Max history set by <Toolkit_LogMaxHistory>; if set to 0 it will just retain the latest log only.
- Kept the -AppendToLogFile parameter in the function - turns out this is required so that we can force enable append when writing to the end of a log …
> Add log rotation to replace 'DoNotAppend' changes

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
These functions wrap the existing Copy-File and Remove-File functions, performing the actions against each user profile path.
> Add functions Copy-FileToUserProfiles and Remove-FileFromUserProfiles

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
This adds a -Wow6432Node switch, which is accepted by all the major registry functions as well as Set-ActiveSetup. The value of the switch is passed through to Convert-RegistryPath which does the grunt work of replacing HKLM\Software with HKLM\Software\Wow6432Node (along with a few special edge cases for Classes keys and Active Setup keys under HKCU).
> Add -Wow6432Node switches for 32-bit registry support

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Previous Robocopy implementation only supported copying folders, and reverted back to native mode if any of the paths in the array $Path were a file.
- Now it asseses each path in the array individually.
- If a * is found in the folder portion, it falls back to native mode still as Robocopy does not accept this.
- If the destination appears to be a file name and doesn't exist as a folder, fall back to native mode which supports copying and renaming files.
- Trim ending backslashes from paths given to Robocopy. I think this was already in and I took it out thinking it was unneccessary, which was a mistake.
- Test-Path -PathType Leaf is used to figure out if the source is a file; which also works for wildcard filenames. Then the path is …
> Copy-File-enhancements

- CHANGELOG.txt
- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
> Update Write-Log Severity parameter description to include 0 = Success

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Issue reported on Discord - Copy-File fails if copying a source of `"$dirFiles\*"` with -Recurse, if the source folder contains subfolders but no files in the root.
If a file is specified in the path (or anything with a wildcard), we're supposed to be splitting the path argument so we can give Robocopy SourceFolder, DestFolder and Files.
Previous code only checked to see if the source contains a file via Test-Path -PathType Leaf. Now it also will hit this code branch if the last portion of the path contains a *.
> Fix for Copy-File

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
old documentation has an incorrect parameter name
> Update documentation for Test-IsMutexAvailable and Get-PEFileArchitecture

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Fixes #938
Resolve-Path now used to fully resolve paths like .\xxx, ..\xxx or \xxx before sending to Robocopy.
Destination folder will now be pre-created if it does not exist, to allow Resolve-Path to work as intended (it was never in there before since Robocopy never required it)
> Dan gough/issue938

- CHANGELOG.txt
- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
- Toolkit/AppDeployToolkit/RunHidden.vbs
- Resolved an issue where Execute-ProcessAsUser was not able to execute with RunLevel = 'LeastPrivilege' in some cases.
- Rewrote RunHidden.vbs to get rid of use of ArrayList as it caused problems on some systems.
- Improved Execute-ProcessAsUser by adding an example for executing the function using "LeastPrivilege".
- Resolved an issue in Execute-ProcessAsUser where the commandline for two of the examples was incorrect.
> Execute process as user enhancements

- Toolkit/AppDeployToolkit/AppDeployToolkitConfig.xml
Fixes #967
Added missing translations for Finnish:
<DeploymentType_Repair>Korjaus</DeploymentType_Re
<Progress_MessageRepair>Korjaus käynnissä. Odota...</Progress_MessageRepair>
These were missing in 3.9.3 also, but it now causes an error in v3.10.0 because we are now calling .Trim() on each element, which fails on $null values.
BTW I ran a check to make sure there are no other missing elements:
```powershell
[xml]$Xml = Get-Content -Path '.\Toolkit\AppDeployToolkit\AppDeployToolkitConfig.xml'
$Properties = ($Xml.AppDeployToolkit_Config.UI_Messages_EN | Get-Member -MemberType Property | Where-Object Name -NE '#comment').Name 
$Languages = ($Xml.AppDeployToolkit_Config | Get-Member -MemberType Property | Where-Object Name -Match '^UI_Messages_(?!EN$)').Name
foreach ($Language in …
```
> Fix critical error for Finnish language

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
- Fixed the text on buttons getting truncated when the display scaling is set to 100% and the string is longer than usual, e.g. Close Programs button when language is set to German.
- Changed the Welcome Dialog so that Defer text strings are split across three labels, allowing the "Time Remaining" string to be bolded.
- Changed the Welcome Dialog so that there is a 10px space between the final text label on the dialog, and the panel containing the Close Programs, Defer and Continue buttons
Fixes: #980
- Bug fix (non-breaking change which fixes an issue)
- Tested by myself and Dan G
> Fixed button font getting cut off in German.

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Set WindowState = 'Normal' has been re-introduced in Show-InstallationPrompt and Show-WelcomePrompt. Without this, the dialogs would remain hidden if executing the toolkit from ConfigMgr executing Powershell.exe directly (and hidden).
Fixes #1004
I tried running a deployment script via ConfigMgr, with this command set to run hidden:
`C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -ExecutionPolicy Bypass -NoProfile -File Deploy-Application.ps1`
The deploy script contains:
```ps
Show-InstallationPrompt -Title "Installation of $appName, v$appVersion" -MessageAlignment Center -Message "Your device will be restarted upon completion. In case you are teleworking, please be advised that this operation will disconnect you from VPN immediately." -ButtonMiddleText "OK" -Icon Information …
```
> Set WindowState = 'Normal' in Show-InstallationPrompt and Show-WelcomePrompt - Fixes #1004

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Add .Trim() to $fileVersion as some uninstall .exes packaged by INNO Setup will have whitespace at the end. 
The variable is a string so the type isn't being changed. 
Fixes: #1006 
Updated a local copy of 3.10.1 with this fix, ran Get-FileVersion -ProductVersion against an uninstaller created by INNO Setup, no whitespace anymore
My apologies if there are issues with this pull request, I'm very new to using Github
> Fix Get-FileVersion -ProductVersion whitespace bug

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
The following line fails in Windows Sandbox due to the computer name being a GUID, and $env:ComputerName containing a truncated form of the full name:
```powershell
[PSADT.QueryUser]::GetUserSessionInfo("$env:ComputerName")
```
Replaced with:
```powershell
[PSADT.QueryUser]::GetUserSessionInfo([System.Net.Dns]::GetHostName())
```
Fixes: #947
Tested that Get-LoggedOnUser as well as a generic Deploy-Application.ps1 script executes successfully in  regular VM as well as Windows Sandbox.
> Fix Get-LoggedOnUser in Windows Sandbox

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
- Service functions now use Get-Service instead of WMI where possible. Only exception is Test-ServiceExists will still use WMI if -PassThru supplied, so that it can return output in the same format as previously, for backwards compatibility. Windows Sandbox does not have the required WMI classes for services available.
- Service functions use 'localhost' as default computer name instead of $env:ComputerName. In Windows Sandbox, this name is truncated and is not the same as the DNS hostname, so fails.
Fixes: #1031
Tested functions work as before in a regular VM and also Windows Sandbox.
> Allow service functions to work in Windows Sandbox

- Toolkit/AppDeployToolkit/AppDeployToolkitMain.ps1
Update `Copy-File` function to use a PowerShell 2 compatible alternative to `Select-Object -SkipLast 1` 
The `-SkipLast` parameter was added to `Select-Object` in PowerShell 5
https://learn.microsoft.com/en-us/previous-versions/powershell/module/microsoft.powershell.utility/select-object?view=powershell-4.0
https://learn.microsoft.com/en-us/previous-versions/powershell/module/microsoft.powershell.utility/select-object?view=powershell-5.0
Dot-sourced AppDeployToolkitMain.ps1 and used `Copy-File` to copy a folder from one location to another.
> Replace Select-Object -SkipLast with PowerShell 2 compatible equivalent

- src/PSAppDeployToolkit/Config/config.psd1
- src/PSAppDeployToolkit/Private/Convert-RegistryKeyToHashtable.ps1
- src/PSAppDeployToolkit/Private/Import-ADTModuleDataFile.ps1
- src/PSAppDeployToolkit/Public/Initialize-ADTModule.ps1
In support of https://github.com/PSAppDeployToolkit/PSAppDeployToolkit4-devel/issues/55, configuration parsing now works in the following fashion:
* Module's default config is imported.
* Caller's config adjacent to their `Invoke-AppDeployToolkit.ps1` script is superimposed over the top.
* Now, registry values defined via Intune or Group Policy are superimposed over the top of those.
This will facilitate mass deployment changes such as dialog styles, etc, without necessarily having to repackage all applications.
Fixes: https://github.com/PSAppDeployToolkit/PSAppDeployToolkit4-devel/issues/55
This has been tested with the relevant registry settings defined in HKEY_LOCAL_MACHINE\SOFTWARE\PSAppDeployToolkit\Config and works as expected.
Supporting ADMX files should be created to support the …
> Allow PSAppDeployToolkit v4.0 config options to be specified via the registry as administrative overrides

- src/PSAppDeployToolkit/Strings/ar/strings.psd1
- src/PSAppDeployToolkit/Strings/cz/strings.psd1
- src/PSAppDeployToolkit/Strings/da/strings.psd1
- src/PSAppDeployToolkit/Strings/de/strings.psd1
- src/PSAppDeployToolkit/Strings/el/strings.psd1
- src/PSAppDeployToolkit/Strings/es/strings.psd1
- src/PSAppDeployToolkit/Strings/fi/strings.psd1
- src/PSAppDeployToolkit/Strings/fr/strings.psd1
- src/PSAppDeployToolkit/Strings/he/strings.psd1
- src/PSAppDeployToolkit/Strings/hu/strings.psd1
- src/PSAppDeployToolkit/Strings/it/strings.psd1
- src/PSAppDeployToolkit/Strings/ja/strings.psd1
- src/PSAppDeployToolkit/Strings/ko/strings.psd1
- src/PSAppDeployToolkit/Strings/nl/strings.psd1
- src/PSAppDeployToolkit/Strings/pl/strings.psd1
- src/PSAppDeployToolkit/Strings/pt-br/strings.psd1
- src/PSAppDeployToolkit/Strings/pt/strings.psd1
- src/PSAppDeployToolkit/Strings/ru/strings.psd1
- src/PSAppDeployToolkit/Strings/sk/strings.psd1
- src/PSAppDeployToolkit/Strings/sv/strings.psd1
- src/PSAppDeployToolkit/Strings/tr/strings.psd1
- src/PSAppDeployToolkit/Strings/zh-hans/strings.psd1
- src/PSAppDeployToolkit/Strings/zh-hant/strings.psd1
We're currently missing all strings for fluent dialogs in all languages other than English. This adds DeepL translations for the missing langauges. Hebrew was performed via Google Translate as it's not a language DeepL offers translation for.
Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration
> Add AI translations via DeepL for all missing language strings.

- src/PSAppDeployToolkit/Public/New-ADTTemplate.ps1
Without shipping copies of these in the frontend, people are going to (and have been) modifying the module that's shipped with the template.
We also now make the module and its files read-only as an attempt to ward off people from modifying the files.
Tested the template generation locally, all working well.
> Add the config/assets/strings folders into the scaffolded template output.

- src/PSAppDeployToolkit/ImportsFirst.ps1
This PR adds the necessary logic to remove the unofficial PSADT module from systems where found, and handles situations whereby the caller may be in PowerShell 7 but the PSADT module was installed via Windows PowerShell 5.x, etc.
It should be noted that this PR does increase the module importation time, especially when the module _is_ present and requires removal. Typical import time for the module is ~3 seconds. Following this change, if PSADT isn't found, ~7 seconds. Following this change and PSADT is found, ~10 seconds.
The penalty of import duration is worth considering as the unofficial PSADT module has been a painful experience and often collides with users and their intention as they don't understand the clobbering aspect of having that module loaded/available while attempting to …
> Unofficial PSADT module cleanup

- docs/Invoke-ADTCommandWithRetries.mdx
- src/PSAppDeployToolkit/Public/Invoke-ADTCommandWithRetries.ps1
This parameter will allow you to retry a command until a given timespan has passed. If both a timespan and a retry limit have been provided it will continue until either one is met.
> Add `-MaximumElapsedTime` parameter to `Invoke-ADTCommandWithRetries`

- src/PSADT/PSADT/Module/PSADT.Module.Class.DeploymentSession.cs
- src/PSAppDeployToolkit/Public/Set-ADTDeferHistory.ps1
- src/PSAppDeployToolkit/Public/Show-ADTInstallationWelcome.ps1
This PR introduces a new parameter, `-DeferRunInterval`, to the `PSAppDeployToolkit` (`Show-ADTInstallationWelcome` and related functions). The feature aims to mitigate repetitive installation attempts by Intune after a user defers an installation, enhancing the overall user experience.
This is a minimally invasive but effective way that addresses the issue.
1. **New Parameter Added:**
- `DeferRunInterval` (as **_System.TimeSpan_**): Specifies the interval before re-prompting the user after a deferral.
- Improves user experience by avoiding multiple immediate retries caused by Intune's default behavior.
- Seamlessly integrates with the existing deferral workflow in `Show-ADTInstallationWelcome`.
2. **Updated Functions:**
- **`Set-ADTDeferHistory`**: Supports saving and retrieving the …
> Add DeferRunInterval to Improve Intune Retry Handling and User Experience with Show-ADTInstallationWelcome Prompt

- src/PSAppDeployToolkit/Public/Get-ADTApplication.ps1
The function `Get-ADTApplication` was failing with the following error when processing uninstall data from the registry:
```
:: Failed to process the uninstall data [HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\{anything}]: The property 'DisplayName' cannot be found on this object. Verify that the property exists.
Error Record:
-------------
 
Message               : The property 'DisplayName' cannot be found on this object. Verify that the property exists.
                        
FullyQualifiedErrorId : PropertyNotFoundStrict,Get-ADTApplication
ScriptStackTrace      : at <ScriptBlock>, C:\Users\path\to\PSAppDeployToolkit\PSAppDeployToolkit.psm1: line 6903
```
- The error was caused by referencing prior `$_` in the `NameMatch`.
- The `$_` reference was outdated …
> - Resolve properties not found error in `Get-ADTApplication`

- docs/Show-ADTInstallationWelcome.mdx
- examples/VLC/Invoke-AppDeployToolkit.ps1
- examples/VLC/README.md
- examples/WinSCP/Invoke-AppDeployToolkit.ps1
- examples/WinSCP/README.md
- src/PSAppDeployToolkit/Frontend/v3/AppDeployToolkit/AppDeployToolkitMain.ps1
- src/PSAppDeployToolkit/Private/Show-ADTWelcomePromptClassic.ps1
- src/PSAppDeployToolkit/Private/Show-ADTWelcomePromptFluent.ps1
- src/PSAppDeployToolkit/Public/Show-ADTInstallationWelcome.ps1
Currently, there is an inconsistency between the parameters of `Show-ADTInstallationWelcome` and `Show-ADTInstallationPrompt` in that the former contains a switch named `-NoMinimizeWindows` and the latter contains `-MinimizeWindows`. This situation arose during the development of v4 as `Show-ADTInstallationWelcome` had `-MinimizeWindows` defaulting to `$true`, while `Show-ADTInstallationPrompt` had `-MinimizeWindows` defaulting to `$false`.
The parameters between these functions should be in a uniform state, and because minimizing windows could be significantly undesirable to many folk, it's safer to make `Show-ADTInstallationWelcome` default to not minimizing windows instead of doing the reverse against `Show-ADTInstallationPrompt`.
This PR has been prompted by …
> Deprecate `Show-ADTInstallationWelcome`'s `-NoMinimizeWindows` and replace with `-MinimizeWindows` to match `Show-ADTInstallationPrompt`.

- src/PSADT.UserInterface/PSADT.UserInterface/UserInterface/PSADT.UserInterface.ADTApplication.cs
- src/PSADT.UserInterface/PSADT.UserInterface/UserInterface/PSADT.UserInterface.BaseDialog.cs
- src/PSADT.UserInterface/PSADT.UserInterface/UserInterface/PSADT.UserInterface.CustomDialog.xaml.cs
- src/PSADT.UserInterface/PSADT.UserInterface/UserInterface/PSADT.UserInterface.ProgressDialog.xaml.cs
- src/PSADT.UserInterface/PSADT.UserInterface/UserInterface/PSADT.UserInterface.RestartDialog.xaml.cs
- src/PSADT.UserInterface/PSADT.UserInterface/UserInterface/PSADT.UserInterface.WelcomeDialog.xaml.cs
PSADT windows can be closed by right-clicking taskbar icon and selecting "Close Window".
> Fix #1261. PSADT windows can be closed from taskbar

- src/PSAppDeployToolkit/Frontend/v4/Invoke-AppDeployToolkit.ps1
In v3, a failed install would not show any error details to the user.
In v4.0, a full stack trace is shown:
This change adds an alternative option to show a simpler message in a themed dialog box:
We had a number of users asking how to hide these errors from the users, so the template comments both options out by default to quieten things down as they were in v3. Users can decide to enable one or the other if they wish - and the docs should be updated to point this out.
> Template error dialog changes

- src/PSAppDeployToolkit/Config/config.psd1
The default exit code of 60012 when a user hits defer is not recognised by Intune or ConfigMgr, so it just shows the status as Failed with the details as '0x8007EA6C':
Changing this to 1602, which is the standard MSI exit code for 'user cancelled the installation', means that both Intune and ConfigMgr are able to interpret this and provide a more informative error message:
A short poll was put on the Discord community and the idea was well received:
> Change default DeferExitCode to 1602

- src/PSAppDeployToolkit/ADMX/en-US/PSAppDeployToolkit.adml
- src/PSAppDeployToolkit/Config/config.psd1
The previous value, while cool by showing a msiexec.exe progress bar without the ability to cancel/stop in any way, is not always properly honoured by vendors who can still display modal dialogs in this mode. This is only truly addressed by using `/qn` to fully silence a deployment.
> Change default msiexec.exe parameters from `/qb-!` to `/qn`

- src/PSAppDeployToolkit/Public/Block-ADTAppExecution.ps1
- src/PSAppDeployToolkit/Public/Show-ADTInstallationWelcome.ps1
> Add warning within `Block-ADTAppExecution` if generated command line is > 255 chars.

- src/PSAppDeployToolkit/Public/Start-ADTMspProcess.ps1
> Set default parameter set for `Start-ADTMspProcess`.

- src/PSAppDeployToolkit/Public/Set-ADTItemPermission.ps1
Last push to this function (https://github.com/PSAppDeployToolkit/PSAppDeployToolkit/pull/1686) used a non-existent $Path variable that triggered an error when using the newly added `-DisableInheritance` parameter. Simple typo, it should've been $LiteralPath. This new param was also missing from the built-in help (which I would've expected to cause a build failure?).
> Set-ADTItemPermission - Correct typo on $LiteralPath variable and update help

- src/PSAppDeployToolkit/Public/Set-ADTItemPermission.ps1
> Avoid `Get-Acl`/`Set-Acl` cmdlets in PowerShell as they have inappropriate permissions testing.

- src/PSAppDeployToolkit/Public/Set-ADTActiveSetup.ps1
> Remove unnecessary filtration from within `Set-ADTActiveSetup -PurgeActiveSetupKey` workflow.

- src/PSAppDeployToolkit/Private/Get-ADTClientServerUser.ps1
- src/PSAppDeployToolkit/Public/Start-ADTMsiProcessAsUser.ps1
- src/PSAppDeployToolkit/Public/Start-ADTMspProcessAsUser.ps1
- src/PSAppDeployToolkit/Public/Start-ADTProcessAsUser.ps1
This only applies for this aspect of the code. For any other client/server process such as the UI, only an active user object would be returned.
> Allow `Start-ADT*ProcessAsUser` to operate with any valid user, such as disconnected users.

- src/PSAppDeployToolkit/Public/Close-ADTSession.ps1
For https://discourse.psappdeploytoolkit.com/t/silent-install-with-restart-and-close-processes-prompt/6906/7.
> Expose `Exit-ADTInvocation`'s `-NoShellExit` parameter on `Close-ADTSession`.

- src/PSAppDeployToolkit/Public/Resolve-ADTErrorRecord.ps1
There's bugs in `Out-String` that can lead to strings with infinitely long trailing lines depending on how wide the output is to be. We resolve this by streaming the output to reduce memory load, and by reducing the width maximum 16-bit value, as we don't need 2147483647 columns here.
> Fix `OutOfMemoryException` issues within `Resolve-ADTErrorRecord`.

- src/PSAppDeployToolkit/Frontend/v4/Invoke-AppDeployToolkit.ps1
> Remove `-MessageAlignment` from commented out `Show-ADTInstallationPrompt` example in template.

- src/PSAppDeployToolkit/Public/Get-ADTExecutableInfo.ps1
> Fix bad comment-based help for `Get-ADTExecutableInfo`.

- src/PSAppDeployToolkit/Private/Close-ADTClientServerProcess.ps1
- src/PSAppDeployToolkit/Public/Close-ADTInstallationProgress.ps1
- src/PSAppDeployToolkit/Public/Unblock-ADTAppExecution.ps1
The result of `$MyInvocation.MyCommand` is referentially different to what's obtained via `Get-Command` when used to populate the CommandTable during module import.
> Ensure all callbacks removed via `Remove-ADTModuleCallback` are referenced by the CommandTable entry.

- src/PSAppDeployToolkit/Public/New-ADTValidateScriptErrorRecord.ps1
Resolves https://discord.com/channels/618712310185197588/627204361545842688/1418245355081957406.
Before
```
PS C:\Repos\PSAppDeployToolkit\src> & .\PSAppDeployToolkit\Frontend\v4\Invoke-AppDeployToolkit.ps1
New-ADTValidateScriptErrorRecord : Cannot process argument transformation on parameter 'TargetName'. Cannot convert value to type System.String.
At C:\Repos\PSAppDeployToolkit\src\PSAppDeployToolkit\Public\Open-ADTSession.ps1:375 char:46
+ ... atingError((New-ADTValidateScriptErrorRecord -ParameterName AppProces ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : InvalidData: (:) [New-ADTValidateScriptErrorRecord], ParameterBindingArgumentTransformationException
+ FullyQualifiedErrorId : …
```
> Explicitly call `.ToString()` for TargetName within `New-ADTValidateScriptErrorRecord` as some types won't implicitly do this.

- src/PSAppDeployToolkit/Public/Show-ADTInstallationPrompt.ps1
> Advise that `-Icon` is not supported with fluent `Show-ADTInstallationPrompt` dialogs.
